version: '3.5'

services:
  php:
    build: ./docker/php
    container_name: dev-eval-php
    environment:
      XDEBUG_CONFIG: "zend_extension=xdebug.so profiler_enable=1 remote_enable=1 remote_handler=dbgp remote_mode=req remote_host=host.docker.internal remote_port=9000 remote_autostart=1 remote_connect_back=1 idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - .:/var/www
  nginx:
    image: nginx:alpine
    container_name: dev-eval-nginx
    ports:
      - 81:80
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
  database:
    image: mysql:latest
    container_name: dev-eval-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data/mysqldata:/var/lib/mysql
    ports:
      - "3307:3307"
networks:
  default:
    name: dev-eval
    driver: bridge

